title: Machine Learning and Reinforcement Learning Eductional Material.
description: A website with machine learning and reinforcement learning eductional material.
theme: just-the-docs

url: https://ml-rl.github.io/ml-rl

aux_links:
  Template Repository: https://ml-rl.github.io/ml-rl
